# 插件元数据
group=top.mc506lw.rebar
main-class=top.mc506lw.rebar.endfield_industry.EndfieldIndustry
version=1.0.0

# 依赖版本
rebar.version=0.42.1-26.1
minecraft.version=26.1.2
paper.api.version=26.1.2.build.74-stable

# 本地 JDK（仅限本机，其他机器上可删除此行或改为自己的 JDK 路径）
org.gradle.java.home=D:\\java\\zulu25

# 强制 UTF-8 编码（仓库内含有大量中文字符串，勿删除）
org.gradle.jvmargs=-Dfile.encoding=UTF-8
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
